services:
  apicepes:
    build:
      context: ..
      dockerfile: apicepespodologia-website/Dockerfile
    container_name: apicepespodologia-website
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    security_opt:
      - no-new-privileges:true
